export const allArticles = [
    {
        id: 1,
        homepage: true,
        img: '',
        title: 'Vít Krejčí si zlepšil osobní maximum v NBA',
        content: 'Basketbalisté Philadelphie přivítali zpět po zranění svou největší hvězdu. Joel Embiid pomohl 24 body k výhře nad Oklahomou, ale jeho start provázeli před zápasem nejasnosti.Reportér stanice TNT, Jared Greenberg, hlásí, že NBA přezkoumá, jestli Philadelphie neporušila ligová pravidla o hlášení zranění.Nejprve totiž bylo uvedeno, že je Embiidův start proti Thunder vyloučen, ale těsně před utkáním bylo oznámeno, že hrát bude.76ers dostali prvního února od NBA pokutu 75 tisíc dolarů za to, že úřadující MVP nebyl v Denveru 27. ledna vůbec uveden ve zprávě o zranění. Ligové vedení tehdy přihlédlo k opětovnému porušování pravidel ze strany Philadelphie a podobně tomu může být i v tomto případě.Sixers ovšem případná pokuta nemrzí, hlavní pro ně je, že mají svého lídra zpět na hřišti. 30letý centr si na konci ledna poranil meniskus v koleni a nikdo netušil, jestli pro něj náhodou sezóna neskončila. Vrátit se měl na konci základní části, ale vypadá to, že už je v pořádku, i když v utkání působil „vyčerpaným dojmem“.Sixers čeká ve čtvrtek nesmírně důležitý zápas. Svěřenci kouče Nicka Nurse totiž jedou do Miami a pokud by tam prohráli, tak si výrazně zkomplikují případný postup do play off. Phila se momentálně nachází na osmém místě ve Východní konferenci s dostatečným náskokem na deváté Chicago, ale pokud by na Floridě prohrála, tak bude mít s Heat horší vzájemnou bilanci a pravděpodobně by musela hrát předkolo play off.',
    },
    {
        id: 2,
        homepage: true,
        img: '',
        title: 'Wemby zastínil druhý nejvyšší bodový výkon v historii Knicks',
        content: 'V San Antoniu se dnes v noci odehrála pořádná bitva. Knicks prohrávali v Texasu po poločase 57:74, ale nakonec dokázali udělat z utkání pořádné drama, které nakonec rozhodovalo až prodloužení.Na smazaní 21bodového manka se podílel především Jalen Brunson, autor 61 bodů (!), což je druhý nejlepší výkon v historii Knicks.27letý rozehrávač zaostal o jediný bod za klubovým rekordem Carmela Anthonyho z roku 2014. Brunson trefil 25 ze 47 střel z pole a měl + 20 v kolonce statistiky +/-, která sleduje efektivitu hráče na hřišti. Jeho předchozím kariérním maximem bylo 50 bodu proti Suns z 15. prosince loňského roku. Brunson se činil zejména ve druhém poločase, ve kterém nastřílel 38 bodů, čímž vyrovnal Patricka Ewinga z roku 1995 v počtu bodů za poločas. Svými 61 nastřílenými body pak překonal další klubovou legendu - Bernarda Kinga.Nejlepšího střelce utkání ovšem zastínil výkon Victora Wembanyamy, jenž se blýskl 40 body, 20 doskoky, ke kterým přidal také sedm asistencí. Francouzský mladík se stal prvním nováčkem s bilancí 40+20 od Shaqa O\'Neala v roce 1993. Wemby trefil v prodloužení za stavu 125:124 rozhodující trojku a Spurs nakonec vyhráli 130:126, protože Brunson tříbodovou střelu v závěru neproměnil.Podle statistik ESPN se teprve podruhé v historii stalo, aby měl jeden hráč na svém kontě minimálně 60 bodů a druhý zaznamenal 40+20. Poprvé se tak stalo v roce 1961, kdy si Elgin Baylor připsal 63 bodů a Wilt Chamberlain kontroval neuvěřitelným double-double za 78 bodů a 43 doskoků!',
    },
    {
        id: 3,
        img: '',
        homepage: true,
        title: 'LeBron James překonal hranici 40 000 nastřílených bodů v NBA',
        content: 'NBA si včera připomněla 62. výročí stobodového výkonu Wilta Chamberlain a tento den padl další velký rekord. LeBron James totiž pokořil hranici 40 000 nastřílených bodů, což se ještě nikomu nepodařilo.LeBronovi chybělo před zápasem s Denverem k této metě devět bodů a nikdo nepochyboval, že se v tomto utkání zapíše zlatým písmem do historie NBA. „Cítím se skvěle a jsem schopný stále hrát jako před deseti lety,“ řekl James po prohře s Nuggets 114:124. Čtyřnásobný šampión zaznamenal ve svém rekordním utkání 26 bodů a celkově už má na svém kontě úctyhodných 40 017 bodů.  „Nikomu se to ještě nepodařilo,“ řekl James začátkem tohoto týdne, když se ho novináři zeptali na další blížící se milník. „Já si hlavně velmi vážím toho, že můžu stále pokračovat v kariéře a dělat co mě baví. Mám tu čest srovnávat se s nejlepšími, kteří tuhle ligy kdy hráli, což byl vždy můj velký sen.“ Nejlepšímu hráči této generace se na začátku druhé čtvrtiny po pokoření magické hranice dostalo velkých ovací od publika. Během následujícího timeoutu byl Jamesovi podán míč na památku a v šatně po zápase pak 39letý basketbalista pózoval, držící bílý papír s ručně napsaným „40 000“, což je odkaz na Chamberlainovu ikonickou fotografii z 2. března 1962. Hvězda Lakers se před rokem (7. února) stala nejlepším střelcem ligy, když překonala celkový počet 38 387 bodů slavného Kareema Abdul-Jabbara. V letošní sezóně odehrál bývalý hráč Clevelandu a Miami 53 utkání s průměrem 25,3 bodu a je zajímavostí, že mu od mu nováčkovské sezóny 2003/04 nikdy neklesl průměr pod 25 bodu na zápas!Jamesovi se v současnosti nikdo nepřibližuje. Žádný aktivní hráč nenastřílel ani 30 000 bodů - nejblíž je Kevin Durant s 28 342 body na devátém místě nejlepších střelců ligy. „Kdo by se mu mohl přiblížit?“ reaguje jeho spoluhráč Anthony Davis. „Myslel jsem si, že Steph Curry, ale když se na to podrobněji podívám, tak nikdo. A rozdíl mezi ním a zbytkem ligy se bude jenom zvětšovat.“LeBron však věří, že jeho rekord není nepřekonatelný: „V lize máme spoustu skvělých mladých hráčů, kteří když zůstanou zdraví a hráli by dlouho, tak se jim to může podařit. O překonání rekordním výkonu Oscara Robertsona v počtu triple-double se také dlouho pochybovalo. Máme tu Luku Dončiče a další skvělé hráče...“Další perličkou je, že pokud rodák z Akronu v Ohiu překoná nějaký velký milník, tak vždy prohraje, což bylo po prohře s Denverem také velké téma v kabině Lakers. Jeho 30 000. bod přišel po prohře se San Antoniem Spurs v roce 2018. Hranici 35 000 nastřílených bodů pokořil v prohraném utkání s Brooklynem v únoru 2021.Když v březnu 2019 překonal Michaela Jordana na čtvrtém místě historického bodování, přišla opět prohra proti Nuggets. Podobně se mu vedlo při pokoření Kobeho Bryanta, kdy Lakers nestačili na Philadelphii. Další porážka přišla také po vyrovnání slavného výkonu Karla Malona (s Washingtonem) a již zmiňovaného Abdula-Jabbara, kdy se jeho tým musel po rekordu sklonit před Oklahomou.',
    },
    {
        id: 4,
        img: '',
        title: 'Článek 4',
        content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!',
    },
    {
        id: 5,
        img: '',
        title: 'OH 2024: Turnaj v Paříži byl rozlosován. USA a souboj se Srbskem',
        content: 'V úterý proběhlo losování basketbalového turnaje, který se uskuteční koncem července v rámci olympijských her v Paříži. Do Francie se kvalifikovalo osm mužstev, čtyři další si musí účast vybojovat v kvalifikačním turnaji. Favoritem jsou Spojené státy americké, které budu chtít odčinit neúspěch z minulého mistrovství světa, které překvapivě vyhrálo Německo. SKUPINA A:  * Austrálie (5) * Kanada (7) * Vítěz kvalifikace ve Španělsku - Španělsko (2), Polsko (15), Finsko (20), Libanon (28), Angola (34) nebo Bahamy (57). * Vítěz kvalifikace v Řecku - Slovinsko (11), Řecko (14), Dominikánská republika (19), Nový Zéland (21), Chorvatsko (30) nebo Egypt (40)  SKUPINA B:  * Německo (3) * Francie (9) * Japonsko (26)* Vítěz kvalifikace v Lotyšsku - Lotyšsko (6), Brazílie (12), Černá Hora (17), Gruzie (23), Filipíny (37) nebo Kamerun (68)   SKUPINA C:* USA (1)* Srbsko (4)* Jižní Súdán (33)* Vítěz kvalifikace v Portoriku - Litva (10), Itálie (13), Portoriko (16), Mexiko (25), Pobřeží slonoviny (31) nebo Bahrajn (67)(pozn. V závorce je uvedeno pořadí ve světovém žebříčku, z kvalifikačních turnajů postoupí pouze vítěz.)Ve skupinové fázi čekají každý tým tři zápasy. Do čtvrtfinále postoupí první a druhý, plus dva nejlepší celky ze třetích míst. Spojené státy budou usilovat o páté zlato v řadě za sebou, ačkoli Američané na mistrovství světa v letech 2019 a 2023 medaili nezískali. Soupisky se budou teprve tvořit, ale na turnaji v Paříži bychom měli vidět hrát nejlepší hráče.',
    },
    {
        id: 6,
        img: '',
        homepage: true,
        title: 'Starší syn LeBrona Jamese se rozhodl přihlásit do draftu NBA',
        content: 'Starší syn basketbalové hvězdy LeBrona Jamese Bronny se rozhodl přihlásit se do letošního draftu NBA. Devatenáctiletý rozehrávač týmu univerzity Jižní Kalifornie na Instagramu zároveň uvedl, že si ponechá možnost pokračovat ve vysokoškolské kariéře. Draft se bude konat 26. a 27. června. Jeho rozbíhající se sportovní dráhu loni v létě narušily zdravotní problémy. V červenci ho na tréninku univerzitního týmu postihla srdeční zástava. Vyšetření odhalila vrozenou vadu. K basketbalu se Bronny James mohl vrátit po čtyřech měsících. „Byl to rok s několika vzestupy a pády, ale všechno mi to pomohlo růst jako člověku, studentovi i sportovci,“ uvedl syn nejlepšího střelce v historii NBA. „Díky USC za úžasný první rok a jako vždy děkuji rodině, přátelům, lékařům, trenérům a fanouškům za podporu.“ Devětatřicetiletý LeBron James je čtyřnásobným šampionem NBA. Minulý měsíc v dresu Los Angeles Lakers jako první hráč v zámořské lize překonal hranici 40 000 bodů. V minulosti se nechal slyšet, že by rád končil kariéru v jednom týmu se svým synem. Má ještě o tři roky mladšího Bryce, který také hraje basketbal a na draft by mohl jít nejdříve v roce 2026.',
    },
    {
        id: 7,
        img: '',
        homepage: true,
        title: 'Krejčí ztratil místo v základu, ale blýskl se netradičním kouskem',
        content: 'Basketbalisté Atlanty prohráli na hřišti Dallasu 95:109 a zůstali na desáté příčce Východní konference NBA, za devátým Chicagem mají o prohru více. Český reprezentant v dresu Hawks Vít Krejčí nastoupil do utkání znovu jen z lavičky a za 15 minut stihl čtyři body, dva doskoky a tři asistence. Obhájci titulu z Denveru prohráli v Los Angeles s Clippers 100:102 a přišli o první místo v Západní konferenci. Atlanta začala v Dallasu dobře a vedla na začátku druhé čtvrtiny o osm bodů. Mavericks však pod taktovkou hvězdného dua Kyrie Irving, Luka Dončič převzali od druhé čtvrtiny iniciativu, postupně utekli na 17 bodů a výhru už si hlídali. Irving k tomu přispěl 26 body, Dončič 25 body, přestože v první čtvrtině nedal ani bod. Dallas si výhrou zajistil účast minimálně v předkole play off, nyní má na pátém místě náskok jedné výhry na šestou a sedmou pozici. Krejčí, který v minulém utkání přišel i přes dobré výkony o pozici v základní sestavě, se střelecky prosadil jen jednou, když v první čtvrtině proměnil trojku s faulem a následně i trestný hod. V tu chvíli poslal Hawks do vedení. Denver se mohl v případě výhry osamostatnit v čele Západní konference, jenže prohrál s Clippers a přepustil první místo Minnesotě. Clippers se naopak přiblížili jistotě play off, na čtvrté pozici mají náskok už tří výher na příčky pro předkolo. Denver opět táhl Nikola Jokič, jenž nasbíral 36 bodů, 17 doskoků a 10 asistencí, ale ani on porážku neodvrátil. Minutu před koncem sice trojkou snížil na rozdíl dvou bodů, jenže Clippers, hrající bez Kawhiho Leonarda, už těsnou výhru uhájili. Denver už si nevypracoval dobrou pozici, jen těžkou trojku Jokiče v poslední sekundě, s níž srbský pivot neuspěl. Paul George pomohl Clippers 28 body.Basketbalisté Golden State zvládli přímý souboj o předkolo a vyhráli v Houstonu 133:110, Steph Curry i Klay Thompson dali po 29 bodech. Warriors tak mají na desáté příčce západu náskok na jedenáctý Houston už čtyři výhry a jsou hodně blízko jistotě předkola. Do konce základní části chybí oběma týmům už jen šest zápasů.„Na tabulku jsme teď vůbec nemysleli. Užíváme si, že hrajeme dobrý basket a že máme dobrou sérii výher. Chceme si to přenést i do zbylých šesti zápasů a uvidíme, co se stane,“ řekl trenér Golden State Steve Kerr, jehož svěřenci vyhráli pošesté za sebou.Philadelphia udolala Miami 109:104 a dotáhla se na něj ve vyrovnaném boji o šestou příčku. Tu nyní drží Indiana, ale Miami i Philadelphia ztrácejí jedinou výhru. Tyrese Maxey k výhře Sixers přispěl 37 body, devíti doskoky a 11 asistencemi. Joel Embiid přidal 29 bodů.',
    },
    {
        id: 8,
        img: '',
        homepage: true,
        title: 'Konec v NBA se blíží, připustila hvězda Lakers James',
        content: 'Nejlepší střelec v historii NBA LeBron James připustil, že se blíží konec jeho basketbalové kariéry. Hvězda Los Angeles Lakers to uvedla po nedělním utkání na hřišti Brooklynu, v němž 40 body přispěla k vítězství hostů 116:104. Po 39. narozeninách pokořil James tuto hranici podruhé, což se před ním povedlo jen další legendě Michaelu Jordanovi, který to dokázal třikrát. Jordan ukončil kariéru ve 40 letech.    „Moc dlouho už hrát nebudu. Dalších jednadvacet let to nebude, to je jisté. Nevím, kdy ten konec přijde, ale moc času už mi nezbývá,“ řekl James novinářům.V Lakers mu po sezoně vyprší dvouletá smlouva na 97 milionů dolarů s hráčskou opcí na příští ročník. Podle spekulací médií nejspíš bude pokračovat. V minulosti čtyřnásobný šampion NBA a dvojnásobný olympijský vítěz uvedl, že by rád odehrál poslední sezonu v jednom týmu se svým synem. Devatenáctiletý Bronny může jít na draft letos, o tři roky mladšího Bryce by si mohl některý z klubů vybrat nejdříve v roce 2026.Ve svém 1485. utkání v kariéře si James devíti trojkami z deseti pokusů vyrovnal osobní rekord. „S tím se dá těžko něco dělat,“ komentoval jeho bilanci při střelbě z dálky Cam Thomas, jenž byl s 30 body nejlepším střelcem Brooklynu.James má v této sezoně úspěšnost ve střelbě za tři body 41,6 procenta, nejlepší v kariéře. S věkem čtyřnásobný nejužitečnější hráč ligy přizpůsobil svoji hru, která už není tak fyzická.„Nemusím se opírat o trojky, protože toho umím dost. Dokážu skórovat kdekoli, jakmile přejdu polovinu hřiště. Ale je třeba se posouvat a pracovat na věcech, které se v lize mění. A tahle soutěž je hodně o trojkách,“ prohlásil James. „Nepatřím k těm, co vystřelí 15 trojek za zápas. Ale chci mít respekt a týmy se mnou při hře zvenku musí počítat,“ dodal.',
    },

];

export const playersStatsGlossary = [
    { term: 'GP', definition: 'Games Played - Odehrané zápasy' },
    { term: 'MIN', definition: 'Minutes Played - Odehrané minuty' },
    { term: 'PTS', definition: 'Points - Body' },
    { term: 'FGM', definition: 'Field Goals Made - úspěšný střelecký pokus z pole' },
    { term: 'FGA', definition: 'Field Goals Attempted - střelecký pokus z pole' },
    { term: 'FG%', definition: 'Field Goal Percentage - úspěšnost střelby z pole (%)' },
    { term: '3PM', definition: '3 Point Field Goals Made - úspěšný střelecký pokus za 3 body' },
    { term: '3PA', definition: '3 Point Field Goals Attempted - střelecký pokus za 3 body' },
    { term: '3P%', definition: '3 Point Field Goal Percentage - úspěšnost střelby za 3 body (%)' },
    { term: 'FTM', definition: 'Free Throws Made - úspěšný střelecký pokus (trestný hod)' },
    { term: 'FTA', definition: 'Free Throws Attempted - střelecký pokus (trestný hod)' },
    { term: 'FT%', definition: 'Free Throw Percentage -  úspěšnost trestných hodů (%)' },
    { term: 'OREB', definition: 'Offensive Rebounds - útočné doskoky' },
    { term: 'DREB', definition: 'Defensive Rebounds - obranné doskoky' },
    { term: 'REB', definition: 'Rebounds - doskoky' },
    { term: 'AST', definition: 'Assists - asistence' },
    { term: 'TOV', definition: 'Turnovers - ztráty míče' },
    { term: 'STL', definition: 'Steals - zisk míče' },
    { term: 'BLK', definition: 'Blocks - bloky' },
    { term: 'PF', definition: 'Personal Fouls - osobní chyby' },
    { term: '+/-', definition: 'Plus-Minus - statistika účasti na palubovce při vstřelených(+) a obdržených(-) bodech' },
];

export const teamsStatsGlossary = [
    { term: 'GP', definition: 'Games Played - Odehrané zápasy' },
    { term: 'W', definition: 'Wins - Výhry' },
    { term: 'L', definition: 'Losses - Prohry' },
    { term: 'W%', definition: 'Wins percentage - Výhry (%)' },
    { term: 'PTS', definition: 'Points - Body' },
    { term: 'FGM', definition: 'Field Goals Made - úspěšný střelecký pokus z pole' },
    { term: 'FGA', definition: 'Field Goals Attempted - střelecký pokus z pole' },
    { term: 'FG%', definition: 'Field Goal Percentage - úspěšnost střelby z pole (%)' },
    { term: '3PM', definition: '3 Point Field Goals Made - úspěšný střelecký pokus za 3 body' },
    { term: '3PA', definition: '3 Point Field Goals Attempted - střelecký pokus za 3 body' },
    { term: '3P%', definition: '3 Point Field Goal Percentage - úspěšnost střelby za 3 body (%)' },
    { term: 'FTM', definition: 'Free Throws Made - úspěšný střelecký pokus (trestný hod)' },
    { term: 'FTA', definition: 'Free Throws Attempted - střelecký pokus (trestný hod)' },
    { term: 'FT%', definition: 'Free Throw Percentage -  úspěšnost trestných hodů (%)' },
    { term: 'OREB', definition: 'Offensive Rebounds - útočné doskoky' },
    { term: 'DREB', definition: 'Defensive Rebounds - obranné doskoky' },
    { term: 'REB', definition: 'Rebounds - doskoky' },
    { term: 'AST', definition: 'Assists - asistence' },
    { term: 'TOV', definition: 'Turnovers - ztráty míče' },
    { term: 'STL', definition: 'Steals - zisk míče' },
    { term: 'BLK', definition: 'Blocks - bloky' },
    { term: 'PF', definition: 'Personal Fouls - osobní chyby' },
    { term: '+/-', definition: 'Plus-Minus - statistika účasti na palubovce při vstřelených(+) a obdržených(-) bodech' },
];